# Generated by Django 2.0.1 on 2018-01-26 18:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='foundEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('found_item_name', models.CharField(max_length=250)),
                ('found_item_desc', models.CharField(default='', max_length=2000)),
                ('found_item_image', models.FileField(upload_to='')),
                ('found_item_place', models.CharField(default='', max_length=1000)),
                ('found_item_date_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('found_item_post_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='lostEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lost_item_name', models.CharField(max_length=250)),
                ('lost_item_desc', models.CharField(default='', max_length=2000)),
                ('lost_item_image', models.FileField(upload_to='')),
                ('lost_item_place', models.CharField(default='', max_length=1000)),
                ('lost_item_date_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('lost_item_post_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='', max_length=250)),
                ('user_email', models.CharField(default='', max_length=250)),
                ('user_mobile', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='lostentry',
            name='user_pk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lost_found.users'),
        ),
        migrations.AddField(
            model_name='foundentry',
            name='user_pk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lost_found.users'),
        ),
    ]
